<?php

namespace Database\Seeders;

use App\Models\Property;
use App\Models\PropertyImage;
use App\Models\User;
use Illuminate\Database\Seeders\DatabaseSeeder as BaseSeeder;
use Illuminate\Support\Facades\DB;

class RealPropertySeeder extends BaseSeeder
{
    /**
     * Seed the application's database with real property data.
     */
    public function run(): void
    {
        $agent = User::where('email', 'agent@amdernproperties.com')->first();
        $developer = User::where('email', 'developer@amdernproperties.com')->first();
        $owner = User::where('email', 'owner@amdernproperties.com')->first();

        $realProperties = [
            [
                'title' => 'FLAT HOUSE FOR SALE - SSEGUKU KATALE, ENTEBBE ROAD',
                'slug' => 'flat-house-for-sale-sseguku-katale',
                'description' => 'Executive flat house for sale in Sseguku Katale along Entebbe Road. 6 bedrooms, 5 bathrooms, 6 toilets, 4 parking spaces. Fully furnished with modern amenities on 25 decimals of land.',
                'price' => 2100000000,
                'currency' => 'UGX',
                'listing_type' => 'for_sale',
                'property_type' => 'house',
                'bedrooms' => 6,
                'bathrooms' => 5,
                'toilets' => 6,
                'parking' => 4,
                'plot_size' => '25 Decimals',
                'size_sqm' => 500,
                'address' => 'Sseguku Katale, Entebbe Road',
                'city' => 'Entebbe',
                'district' => 'Entebbe',
                'area' => 'Sseguku Katale',
                'features' => ['swimming_pool', 'garden', 'security', 'parking', 'water_tank', 'backup_generator'],
                'serviced' => true,
                'furnished' => true,
                'status' => 'active',
                'is_verified' => true,
                'moderation_status' => 'approved',
                'user_id' => $agent->id,
                'location' => [32.4632, 0.1847],
                'created_at' => '2025-08-20 10:00:00',
            ],
            [
                'title' => 'APARTMENT BLOCK FOR SALE - KYALIWAJJALA',
                'slug' => 'apartment-block-for-sale-kyaliwajjala',
                'description' => 'Block of flats for sale in Kyaliwajjala. 12 units with 12 bedrooms, 12 bathrooms, 8 parking spaces. Excellent investment opportunity on 13 decimals.',
                'price' => 1700000000,
                'currency' => 'UGX',
                'listing_type' => 'for_sale',
                'property_type' => 'apartment',
                'bedrooms' => 12,
                'bathrooms' => 12,
                'toilets' => 12,
                'parking' => 8,
                'plot_size' => '13 Decimals',
                'size_sqm' => 650,
                'address' => 'Kyaliwajjala',
                'city' => 'Kampala',
                'district' => 'Wakiso',
                'area' => 'Kyaliwajjala',
                'features' => ['elevator', 'security', 'parking', 'garden', 'backup_generator'],
                'serviced' => true,
                'furnished' => false,
                'status' => 'active',
                'is_verified' => true,
                'moderation_status' => 'approved',
                'user_id' => $developer->id,
                'location' => [32.5721, 0.3821],
                'created_at' => '2025-08-18 14:30:00',
            ],
            [
                'title' => '3 BEDROOM APARTMENT FOR RENT - KOLOLO',
                'slug' => '3-bedroom-apartment-for-rent-kololo',
                'description' => 'Fully furnished 3-bedroom apartment for rent in Kololo. Modern finishing, secure neighborhood, close to embassies and city center.',
                'price' => 3500000,
                'currency' => 'UGX',
                'listing_type' => 'for_rent',
                'property_type' => 'apartment',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'toilets' => 3,
                'parking' => 2,
                'plot_size' => null,
                'size_sqm' => 120,
                'address' => 'Kololo Hill',
                'city' => 'Kampala',
                'district' => 'Kampala',
                'area' => 'Kololo',
                'features' => ['furnished', 'wifi', 'security', 'parking', 'gym'],
                'serviced' => true,
                'furnished' => true,
                'status' => 'active',
                'is_verified' => true,
                'moderation_status' => 'approved',
                'user_id' => $agent->id,
                'location' => [32.5835, 0.3136],
                'created_at' => '2025-08-15 09:00:00',
            ],
            [
                'title' => 'COMMERCIAL LAND FOR SALE - NAKAWA INDUSTRIAL',
                'slug' => 'commercial-land-for-sale-nakawa',
                'description' => 'Prime commercial land in Nakawa Industrial Area. Perfect for warehouse, factory, or office complex. Ready title with all utilities connected.',
                'price' => 850000000,
                'currency' => 'UGX',
                'listing_type' => 'for_sale',
                'property_type' => 'commercial',
                'bedrooms' => 0,
                'bathrooms' => 0,
                'toilets' => 0,
                'parking' => 0,
                'plot_size' => '50 Decimals',
                'size_sqm' => 2000,
                'address' => 'Nakawa Industrial Area',
                'city' => 'Kampala',
                'district' => 'Kampala',
                'area' => 'Nakawa',
                'features' => ['electricity', 'water', 'road_access', 'security'],
                'serviced' => true,
                'furnished' => false,
                'status' => 'active',
                'is_verified' => true,
                'moderation_status' => 'approved',
                'user_id' => $developer->id,
                'location' => [32.6321, 0.3890],
                'created_at' => '2025-08-10 11:00:00',
            ],
            [
                'title' => 'LUXURY VILLA FOR SALE - MUTUNDWE',
                'slug' => 'luxury-villa-for-sale-mutundwe',
                'description' => 'Stunning 5-bedroom luxury villa in Mutundwe. Features include swimming pool, home theater, gym, and smart home automation. On 30 decimals.',
                'price' => 3500000000,
                'currency' => 'UGX',
                'listing_type' => 'for_sale',
                'property_type' => 'house',
                'bedrooms' => 5,
                'bathrooms' => 4,
                'toilets' => 5,
                'parking' => 3,
                'plot_size' => '30 Decimals',
                'size_sqm' => 750,
                'address' => 'Mutundwe Hill',
                'city' => 'Wakiso',
                'district' => 'Wakiso',
                'area' => 'Mutundwe',
                'features' => ['swimming_pool', 'gym', 'home_theater', 'smart_home', 'security', 'garden', 'parking'],
                'serviced' => true,
                'furnished' => true,
                'status' => 'active',
                'is_verified' => true,
                'moderation_status' => 'approved',
                'user_id' => $owner->id,
                'location' => [32.5234, 0.2543],
                'created_at' => '2025-08-05 16:00:00',
            ],
            [
                'title' => 'RESIDENTIAL PLOT FOR SALE - KIRA',
                'slug' => 'residential-plot-for-sale-kira',
                'description' => '50ft by 100ft residential plot in Kira, well-developed neighborhood with all utilities. Ready for immediate construction.',
                'price' => 180000000,
                'currency' => 'UGX',
                'listing_type' => 'for_sale',
                'property_type' => 'land',
                'bedrooms' => 0,
                'bathrooms' => 0,
                'toilets' => 0,
                'parking' => 0,
                'plot_size' => '50x100 ft',
                'size_sqm' => 450,
                'address' => 'Kira Municipality',
                'city' => 'Kira',
                'district' => 'Wakiso',
                'area' => 'Kira',
                'features' => ['electricity', 'water', 'road_access'],
                'serviced' => true,
                'furnished' => false,
                'status' => 'active',
                'is_verified' => true,
                'moderation_status' => 'approved',
                'user_id' => $owner->id,
                'location' => [32.6543, 0.3456],
                'created_at' => '2025-08-01 08:00:00',
            ],
            [
                'title' => 'OFFICE SPACE FOR RENT - KAMPALA CBD',
                'slug' => 'office-space-for-rent-kampala-cbd',
                'description' => 'Premium office space in Kampala Central Business District. 200 sqm open plan office with 5 private offices, conference room, and reception.',
                'price' => 5200000,
                'currency' => 'UGX',
                'listing_type' => 'for_rent',
                'property_type' => 'commercial',
                'bedrooms' => 0,
                'bathrooms' => 2,
                'toilets' => 3,
                'parking' => 5,
                'plot_size' => null,
                'size_sqm' => 200,
                'address' => 'Kampala CBD, Jinja Road',
                'city' => 'Kampala',
                'district' => 'Kampala',
                'area' => 'CBD',
                'features' => ['wifi', 'security', 'parking', 'elevator', 'air_conditioning'],
                'serviced' => true,
                'furnished' => true,
                'status' => 'active',
                'is_verified' => true,
                'moderation_status' => 'approved',
                'user_id' => $agent->id,
                'location' => [32.5835, 0.3136],
                'created_at' => '2025-07-28 13:00:00',
            ],
            [
                'title' => '2 BEDROOM APARTMENT FOR RENT - BUKOTO',
                'slug' => '2-bedroom-apartment-for-rent-bukoto',
                'description' => 'Cozy 2-bedroom apartment for rent in Bukoto. Close to Kampala International Hospital and shopping centers.',
                'price' => 1800000,
                'currency' => 'UGX',
                'listing_type' => 'for_rent',
                'property_type' => 'apartment',
                'bedrooms' => 2,
                'bathrooms' => 1,
                'toilets' => 2,
                'parking' => 1,
                'plot_size' => null,
                'size_sqm' => 85,
                'address' => 'Bukoto',
                'city' => 'Kampala',
                'district' => 'Kampala',
                'area' => 'Bukoto',
                'features' => ['wifi', 'security', 'parking'],
                'serviced' => true,
                'furnished' => false,
                'status' => 'active',
                'is_verified' => true,
                'moderation_status' => 'approved',
                'user_id' => $agent->id,
                'location' => [32.5934, 0.3234],
                'created_at' => '2025-07-25 10:00:00',
            ],
            [
                'title' => 'LAND FOR SALE - JINJA ROAD, BUKASA',
                'slug' => 'land-for-sale-jinja-road-bukasa',
                'description' => '100ft by 100ft residential plot along Jinja Road in Bukasa. Rapidly developing area with excellent road network.',
                'price' => 450000000,
                'currency' => 'UGX',
                'listing_type' => 'for_sale',
                'property_type' => 'land',
                'bedrooms' => 0,
                'bathrooms' => 0,
                'toilets' => 0,
                'parking' => 0,
                'plot_size' => '100x100 ft',
                'size_sqm' => 900,
                'address' => 'Jinja Road, Bukasa',
                'city' => 'Kampala',
                'district' => 'Kampala',
                'area' => 'Bukasa',
                'features' => ['electricity', 'water', 'road_access'],
                'serviced' => true,
                'furnished' => false,
                'status' => 'active',
                'is_verified' => true,
                'moderation_status' => 'approved',
                'user_id' => $developer->id,
                'location' => [32.6123, 0.3421],
                'created_at' => '2025-07-20 15:00:00',
            ],
            [
                'title' => 'STUDIO APARTMENT FOR RENT - NTINDA',
                'slug' => 'studio-apartment-for-rent-ntinda',
                'description' => 'Modern studio apartment for rent in Ntinda. Perfect for young professionals. Fully furnished with all amenities.',
                'price' => 900000,
                'currency' => 'UGX',
                'listing_type' => 'for_rent',
                'property_type' => 'apartment',
                'bedrooms' => 1,
                'bathrooms' => 1,
                'toilets' => 1,
                'parking' => 1,
                'plot_size' => null,
                'size_sqm' => 35,
                'address' => 'Ntinda',
                'city' => 'Kampala',
                'district' => 'Kampala',
                'area' => 'Ntinda',
                'features' => ['furnished', 'wifi', 'security', 'parking'],
                'serviced' => true,
                'furnished' => true,
                'status' => 'active',
                'is_verified' => true,
                'moderation_status' => 'approved',
                'user_id' => $agent->id,
                'location' => [32.6012, 0.3547],
                'created_at' => '2025-07-15 09:00:00',
            ],
            [
                'title' => 'COMMERCIAL WAREHOUSE FOR RENT - NAMANVE',
                'slug' => 'commercial-warehouse-for-rent-namanve',
                'description' => '5000 sqm warehouse for rent in Namanve Industrial Park. High ceiling, loading docks, 24/7 security, and ample parking.',
                'price' => 15000000,
                'currency' => 'UGX',
                'listing_type' => 'for_rent',
                'property_type' => 'commercial',
                'bedrooms' => 0,
                'bathrooms' => 2,
                'toilets' => 4,
                'parking' => 20,
                'plot_size' => null,
                'size_sqm' => 5000,
                'address' => 'Namanve Industrial Park',
                'city' => 'Kampala',
                'district' => 'Kampala',
                'area' => 'Namanve',
                'features' => ['security', 'parking', 'electricity', 'water', 'loading_docks'],
                'serviced' => true,
                'furnished' => false,
                'status' => 'active',
                'is_verified' => true,
                'moderation_status' => 'approved',
                'user_id' => $developer->id,
                'location' => [32.6854, 0.4123],
                'created_at' => '2025-07-10 12:00:00',
            ],
            [
                'title' => '4 BEDROOM HOUSE FOR RENT - MENGOMBALA',
                'slug' => '4-bedroom-house-for-rent-mengombala',
                'description' => 'Spacious 4-bedroom house for rent in Mengo. Close to Mengo Hospital and Kampala Capital City Authority.',
                'price' => 2800000,
                'currency' => 'UGX',
                'listing_type' => 'for_rent',
                'property_type' => 'house',
                'bedrooms' => 4,
                'bathrooms' => 3,
                'toilets' => 4,
                'parking' => 2,
                'plot_size' => null,
                'size_sqm' => 180,
                'address' => 'Mengo',
                'city' => 'Kampala',
                'district' => 'Kampala',
                'area' => 'Mengo',
                'features' => ['garden', 'security', 'parking', 'water_tank'],
                'serviced' => true,
                'furnished' => false,
                'status' => 'active',
                'is_verified' => true,
                'moderation_status' => 'approved',
                'user_id' => $owner->id,
                'location' => [32.5621, 0.3123],
                'created_at' => '2025-07-05 14:00:00',
            ],
        ];

        foreach ($realProperties as $propData) {
            $property = Property::create($propData);

            // Add 2-3 images per property
            $imageCount = rand(2, 3);
            for ($i = 0; $i < $imageCount; $i++) {
                PropertyImage::create([
                    'property_id' => $property->id,
                    'image_url' => "/property-media/property-{$property->id}-" . ($i + 1) . ".jpg",
                    'image_path' => "property-media/property-{$property->id}-" . ($i + 1) . ".jpg",
                    'is_primary' => $i === 0,
                    'sort_order' => $i,
                ]);
            }
        }
    }
}