/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AreaGuidesRouteImport } from './routes/area-guides'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as ForRentRouteImport } from './routes/for-rent'
import { Route as ForSaleRouteImport } from './routes/for-sale'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ListPropertyRouteImport } from './routes/list-property'
import { Route as MortgageCalculatorRouteImport } from './routes/mortgage-calculator'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as AccountPrivacyRouteImport } from './routes/account.privacy'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAgentsRouteImport } from './routes/admin.agents'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminListingsRouteImport } from './routes/admin.listings'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminPhotosRouteImport } from './routes/admin.photos'
import { Route as AdminRegionsRouteImport } from './routes/admin.regions'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminVerificationRouteImport } from './routes/admin.verification'
import { Route as AdvertiseBannersRouteImport } from './routes/advertise.banners'
import { Route as AdvertiseListingTypesRouteImport } from './routes/advertise.listing-types'
import { Route as AdvertisePremiumPlusRouteImport } from './routes/advertise.premium-plus'
import { Route as AdvertiseVerifiedPhotosRouteImport } from './routes/advertise.verified-photos'
import { Route as AgentsIdRouteImport } from './routes/agents.$id'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardEnquiriesRouteImport } from './routes/dashboard.enquiries'
import { Route as DashboardListingsRouteImport } from './routes/dashboard.listings'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSubscriptionRouteImport } from './routes/dashboard.subscription'
import { Route as ForRentCommercialRouteImport } from './routes/for-rent.commercial'
import { Route as ForRentFlatsApartmentsRouteImport } from './routes/for-rent.flats-apartments'
import { Route as ForRentHousesRouteImport } from './routes/for-rent.houses'
import { Route as ForRentLandRouteImport } from './routes/for-rent.land'
import { Route as ForRentVehiclesRouteImport } from './routes/for-rent.vehicles'
import { Route as ForSaleCommercialRouteImport } from './routes/for-sale.commercial'
import { Route as ForSaleFlatsApartmentsRouteImport } from './routes/for-sale.flats-apartments'
import { Route as ForSaleHousesRouteImport } from './routes/for-sale.houses'
import { Route as ForSaleLandRouteImport } from './routes/for-sale.land'
import { Route as ForSaleVehiclesRouteImport } from './routes/for-sale.vehicles'
import { Route as MarketTrendsDemandRouteImport } from './routes/market-trends.demand'
import { Route as MarketTrendsPricesRouteImport } from './routes/market-trends.prices'
import { Route as MarketTrendsReportsRouteImport } from './routes/market-trends.reports'
import { Route as PaymentsResultRouteImport } from './routes/payments.result'
import { Route as PropertyIdRouteImport } from './routes/property.$id'
import { Route as RequestsNewRouteImport } from './routes/requests.new'
import { Route as AdminListingsNewRouteImport } from './routes/admin.listings.new'
import { Route as DashboardListingsNewRouteImport } from './routes/dashboard.listings.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaGuidesRoute = AreaGuidesRouteImport.update({
  id: '/area-guides',
  path: '/area-guides',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForRentRoute = ForRentRouteImport.update({
  id: '/for-rent',
  path: '/for-rent',
  getParentRoute: () => rootRouteImport,
} as any)
const ForSaleRoute = ForSaleRouteImport.update({
  id: '/for-sale',
  path: '/for-sale',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ListPropertyRoute = ListPropertyRouteImport.update({
  id: '/list-property',
  path: '/list-property',
  getParentRoute: () => rootRouteImport,
} as any)
const MortgageCalculatorRoute = MortgageCalculatorRouteImport.update({
  id: '/mortgage-calculator',
  path: '/mortgage-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPrivacyRoute = AccountPrivacyRouteImport.update({
  id: '/account/privacy',
  path: '/account/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsRoute = AdminListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPhotosRoute = AdminPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegionsRoute = AdminRegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AdminRoute,
} as any)
const AdvertiseBannersRoute = AdvertiseBannersRouteImport.update({
  id: '/advertise/banners',
  path: '/advertise/banners',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseListingTypesRoute = AdvertiseListingTypesRouteImport.update({
  id: '/advertise/listing-types',
  path: '/advertise/listing-types',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertisePremiumPlusRoute = AdvertisePremiumPlusRouteImport.update({
  id: '/advertise/premium-plus',
  path: '/advertise/premium-plus',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseVerifiedPhotosRoute = AdvertiseVerifiedPhotosRouteImport.update({
  id: '/advertise/verified-photos',
  path: '/advertise/verified-photos',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AgentsRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEnquiriesRoute = DashboardEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardListingsRoute = DashboardListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubscriptionRoute = DashboardSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => DashboardRoute,
} as any)
const ForRentCommercialRoute = ForRentCommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => ForRentRoute,
} as any)
const ForRentFlatsApartmentsRoute = ForRentFlatsApartmentsRouteImport.update({
  id: '/flats-apartments',
  path: '/flats-apartments',
  getParentRoute: () => ForRentRoute,
} as any)
const ForRentHousesRoute = ForRentHousesRouteImport.update({
  id: '/houses',
  path: '/houses',
  getParentRoute: () => ForRentRoute,
} as any)
const ForRentLandRoute = ForRentLandRouteImport.update({
  id: '/land',
  path: '/land',
  getParentRoute: () => ForRentRoute,
} as any)
const ForRentVehiclesRoute = ForRentVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => ForRentRoute,
} as any)
const ForSaleCommercialRoute = ForSaleCommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => ForSaleRoute,
} as any)
const ForSaleFlatsApartmentsRoute = ForSaleFlatsApartmentsRouteImport.update({
  id: '/flats-apartments',
  path: '/flats-apartments',
  getParentRoute: () => ForSaleRoute,
} as any)
const ForSaleHousesRoute = ForSaleHousesRouteImport.update({
  id: '/houses',
  path: '/houses',
  getParentRoute: () => ForSaleRoute,
} as any)
const ForSaleLandRoute = ForSaleLandRouteImport.update({
  id: '/land',
  path: '/land',
  getParentRoute: () => ForSaleRoute,
} as any)
const ForSaleVehiclesRoute = ForSaleVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => ForSaleRoute,
} as any)
const MarketTrendsDemandRoute = MarketTrendsDemandRouteImport.update({
  id: '/market-trends/demand',
  path: '/market-trends/demand',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketTrendsPricesRoute = MarketTrendsPricesRouteImport.update({
  id: '/market-trends/prices',
  path: '/market-trends/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketTrendsReportsRoute = MarketTrendsReportsRouteImport.update({
  id: '/market-trends/reports',
  path: '/market-trends/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsResultRoute = PaymentsResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => PaymentsRoute,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsNewRoute = RequestsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RequestsRoute,
} as any)
const AdminListingsNewRoute = AdminListingsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminListingsRoute,
} as any)
const DashboardListingsNewRoute = DashboardListingsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardListingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRouteWithChildren
  '/area-guides': typeof AreaGuidesRoute
  '/blog': typeof BlogRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/developers': typeof DevelopersRoute
  '/for-rent': typeof ForRentRouteWithChildren
  '/for-sale': typeof ForSaleRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/list-property': typeof ListPropertyRoute
  '/mortgage-calculator': typeof MortgageCalculatorRoute
  '/payments': typeof PaymentsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/requests': typeof RequestsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/account/privacy': typeof AccountPrivacyRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/listings': typeof AdminListingsRouteWithChildren
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/photos': typeof AdminPhotosRoute
  '/admin/regions': typeof AdminRegionsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/advertise/banners': typeof AdvertiseBannersRoute
  '/advertise/listing-types': typeof AdvertiseListingTypesRoute
  '/advertise/premium-plus': typeof AdvertisePremiumPlusRoute
  '/advertise/verified-photos': typeof AdvertiseVerifiedPhotosRoute
  '/agents/$id': typeof AgentsIdRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/enquiries': typeof DashboardEnquiriesRoute
  '/dashboard/listings': typeof DashboardListingsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/for-rent/commercial': typeof ForRentCommercialRoute
  '/for-rent/flats-apartments': typeof ForRentFlatsApartmentsRoute
  '/for-rent/houses': typeof ForRentHousesRoute
  '/for-rent/land': typeof ForRentLandRoute
  '/for-rent/vehicles': typeof ForRentVehiclesRoute
  '/for-sale/commercial': typeof ForSaleCommercialRoute
  '/for-sale/flats-apartments': typeof ForSaleFlatsApartmentsRoute
  '/for-sale/houses': typeof ForSaleHousesRoute
  '/for-sale/land': typeof ForSaleLandRoute
  '/for-sale/vehicles': typeof ForSaleVehiclesRoute
  '/market-trends/demand': typeof MarketTrendsDemandRoute
  '/market-trends/prices': typeof MarketTrendsPricesRoute
  '/market-trends/reports': typeof MarketTrendsReportsRoute
  '/payments/result': typeof PaymentsResultRoute
  '/property/$id': typeof PropertyIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/listings/new': typeof AdminListingsNewRoute
  '/dashboard/listings/new': typeof DashboardListingsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRouteWithChildren
  '/area-guides': typeof AreaGuidesRoute
  '/blog': typeof BlogRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/for-rent': typeof ForRentRouteWithChildren
  '/for-sale': typeof ForSaleRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/list-property': typeof ListPropertyRoute
  '/mortgage-calculator': typeof MortgageCalculatorRoute
  '/payments': typeof PaymentsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/requests': typeof RequestsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/account/privacy': typeof AccountPrivacyRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/listings': typeof AdminListingsRouteWithChildren
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/photos': typeof AdminPhotosRoute
  '/admin/regions': typeof AdminRegionsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/advertise/banners': typeof AdvertiseBannersRoute
  '/advertise/listing-types': typeof AdvertiseListingTypesRoute
  '/advertise/premium-plus': typeof AdvertisePremiumPlusRoute
  '/advertise/verified-photos': typeof AdvertiseVerifiedPhotosRoute
  '/agents/$id': typeof AgentsIdRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/enquiries': typeof DashboardEnquiriesRoute
  '/dashboard/listings': typeof DashboardListingsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/for-rent/commercial': typeof ForRentCommercialRoute
  '/for-rent/flats-apartments': typeof ForRentFlatsApartmentsRoute
  '/for-rent/houses': typeof ForRentHousesRoute
  '/for-rent/land': typeof ForRentLandRoute
  '/for-rent/vehicles': typeof ForRentVehiclesRoute
  '/for-sale/commercial': typeof ForSaleCommercialRoute
  '/for-sale/flats-apartments': typeof ForSaleFlatsApartmentsRoute
  '/for-sale/houses': typeof ForSaleHousesRoute
  '/for-sale/land': typeof ForSaleLandRoute
  '/for-sale/vehicles': typeof ForSaleVehiclesRoute
  '/market-trends/demand': typeof MarketTrendsDemandRoute
  '/market-trends/prices': typeof MarketTrendsPricesRoute
  '/market-trends/reports': typeof MarketTrendsReportsRoute
  '/payments/result': typeof PaymentsResultRoute
  '/property/$id': typeof PropertyIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/listings/new': typeof AdminListingsNewRoute
  '/dashboard/listings/new': typeof DashboardListingsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRouteWithChildren
  '/area-guides': typeof AreaGuidesRoute
  '/blog': typeof BlogRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/developers': typeof DevelopersRoute
  '/for-rent': typeof ForRentRouteWithChildren
  '/for-sale': typeof ForSaleRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/list-property': typeof ListPropertyRoute
  '/mortgage-calculator': typeof MortgageCalculatorRoute
  '/payments': typeof PaymentsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/requests': typeof RequestsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/account/privacy': typeof AccountPrivacyRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/listings': typeof AdminListingsRouteWithChildren
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/photos': typeof AdminPhotosRoute
  '/admin/regions': typeof AdminRegionsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/advertise/banners': typeof AdvertiseBannersRoute
  '/advertise/listing-types': typeof AdvertiseListingTypesRoute
  '/advertise/premium-plus': typeof AdvertisePremiumPlusRoute
  '/advertise/verified-photos': typeof AdvertiseVerifiedPhotosRoute
  '/agents/$id': typeof AgentsIdRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/enquiries': typeof DashboardEnquiriesRoute
  '/dashboard/listings': typeof DashboardListingsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/for-rent/commercial': typeof ForRentCommercialRoute
  '/for-rent/flats-apartments': typeof ForRentFlatsApartmentsRoute
  '/for-rent/houses': typeof ForRentHousesRoute
  '/for-rent/land': typeof ForRentLandRoute
  '/for-rent/vehicles': typeof ForRentVehiclesRoute
  '/for-sale/commercial': typeof ForSaleCommercialRoute
  '/for-sale/flats-apartments': typeof ForSaleFlatsApartmentsRoute
  '/for-sale/houses': typeof ForSaleHousesRoute
  '/for-sale/land': typeof ForSaleLandRoute
  '/for-sale/vehicles': typeof ForSaleVehiclesRoute
  '/market-trends/demand': typeof MarketTrendsDemandRoute
  '/market-trends/prices': typeof MarketTrendsPricesRoute
  '/market-trends/reports': typeof MarketTrendsReportsRoute
  '/payments/result': typeof PaymentsResultRoute
  '/property/$id': typeof PropertyIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/listings/new': typeof AdminListingsNewRoute
  '/dashboard/listings/new': typeof DashboardListingsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/agents'
    | '/area-guides'
    | '/blog'
    | '/compare'
    | '/contact'
    | '/dashboard'
    | '/developers'
    | '/for-rent'
    | '/for-sale'
    | '/forgot-password'
    | '/help'
    | '/list-property'
    | '/mortgage-calculator'
    | '/payments'
    | '/privacy'
    | '/privacy-policy'
    | '/register'
    | '/requests'
    | '/reset-password'
    | '/saved'
    | '/search'
    | '/signin'
    | '/terms'
    | '/terms-and-conditions'
    | '/account/privacy'
    | '/admin/agents'
    | '/admin/billing'
    | '/admin/blog'
    | '/admin/leads'
    | '/admin/listings'
    | '/admin/messages'
    | '/admin/photos'
    | '/admin/regions'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verification'
    | '/advertise/banners'
    | '/advertise/listing-types'
    | '/advertise/premium-plus'
    | '/advertise/verified-photos'
    | '/agents/$id'
    | '/api/chat'
    | '/auth/callback'
    | '/dashboard/enquiries'
    | '/dashboard/listings'
    | '/dashboard/settings'
    | '/dashboard/subscription'
    | '/for-rent/commercial'
    | '/for-rent/flats-apartments'
    | '/for-rent/houses'
    | '/for-rent/land'
    | '/for-rent/vehicles'
    | '/for-sale/commercial'
    | '/for-sale/flats-apartments'
    | '/for-sale/houses'
    | '/for-sale/land'
    | '/for-sale/vehicles'
    | '/market-trends/demand'
    | '/market-trends/prices'
    | '/market-trends/reports'
    | '/payments/result'
    | '/property/$id'
    | '/requests/new'
    | '/admin/'
    | '/dashboard/'
    | '/admin/listings/new'
    | '/dashboard/listings/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agents'
    | '/area-guides'
    | '/blog'
    | '/compare'
    | '/contact'
    | '/developers'
    | '/for-rent'
    | '/for-sale'
    | '/forgot-password'
    | '/help'
    | '/list-property'
    | '/mortgage-calculator'
    | '/payments'
    | '/privacy'
    | '/privacy-policy'
    | '/register'
    | '/requests'
    | '/reset-password'
    | '/saved'
    | '/search'
    | '/signin'
    | '/terms'
    | '/terms-and-conditions'
    | '/account/privacy'
    | '/admin/agents'
    | '/admin/billing'
    | '/admin/blog'
    | '/admin/leads'
    | '/admin/listings'
    | '/admin/messages'
    | '/admin/photos'
    | '/admin/regions'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verification'
    | '/advertise/banners'
    | '/advertise/listing-types'
    | '/advertise/premium-plus'
    | '/advertise/verified-photos'
    | '/agents/$id'
    | '/api/chat'
    | '/auth/callback'
    | '/dashboard/enquiries'
    | '/dashboard/listings'
    | '/dashboard/settings'
    | '/dashboard/subscription'
    | '/for-rent/commercial'
    | '/for-rent/flats-apartments'
    | '/for-rent/houses'
    | '/for-rent/land'
    | '/for-rent/vehicles'
    | '/for-sale/commercial'
    | '/for-sale/flats-apartments'
    | '/for-sale/houses'
    | '/for-sale/land'
    | '/for-sale/vehicles'
    | '/market-trends/demand'
    | '/market-trends/prices'
    | '/market-trends/reports'
    | '/payments/result'
    | '/property/$id'
    | '/requests/new'
    | '/admin'
    | '/dashboard'
    | '/admin/listings/new'
    | '/dashboard/listings/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/agents'
    | '/area-guides'
    | '/blog'
    | '/compare'
    | '/contact'
    | '/dashboard'
    | '/developers'
    | '/for-rent'
    | '/for-sale'
    | '/forgot-password'
    | '/help'
    | '/list-property'
    | '/mortgage-calculator'
    | '/payments'
    | '/privacy'
    | '/privacy-policy'
    | '/register'
    | '/requests'
    | '/reset-password'
    | '/saved'
    | '/search'
    | '/signin'
    | '/terms'
    | '/terms-and-conditions'
    | '/account/privacy'
    | '/admin/agents'
    | '/admin/billing'
    | '/admin/blog'
    | '/admin/leads'
    | '/admin/listings'
    | '/admin/messages'
    | '/admin/photos'
    | '/admin/regions'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/verification'
    | '/advertise/banners'
    | '/advertise/listing-types'
    | '/advertise/premium-plus'
    | '/advertise/verified-photos'
    | '/agents/$id'
    | '/api/chat'
    | '/auth/callback'
    | '/dashboard/enquiries'
    | '/dashboard/listings'
    | '/dashboard/settings'
    | '/dashboard/subscription'
    | '/for-rent/commercial'
    | '/for-rent/flats-apartments'
    | '/for-rent/houses'
    | '/for-rent/land'
    | '/for-rent/vehicles'
    | '/for-sale/commercial'
    | '/for-sale/flats-apartments'
    | '/for-sale/houses'
    | '/for-sale/land'
    | '/for-sale/vehicles'
    | '/market-trends/demand'
    | '/market-trends/prices'
    | '/market-trends/reports'
    | '/payments/result'
    | '/property/$id'
    | '/requests/new'
    | '/admin/'
    | '/dashboard/'
    | '/admin/listings/new'
    | '/dashboard/listings/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgentsRoute: typeof AgentsRouteWithChildren
  AreaGuidesRoute: typeof AreaGuidesRoute
  BlogRoute: typeof BlogRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DevelopersRoute: typeof DevelopersRoute
  ForRentRoute: typeof ForRentRouteWithChildren
  ForSaleRoute: typeof ForSaleRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  ListPropertyRoute: typeof ListPropertyRoute
  MortgageCalculatorRoute: typeof MortgageCalculatorRoute
  PaymentsRoute: typeof PaymentsRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RegisterRoute: typeof RegisterRoute
  RequestsRoute: typeof RequestsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  SigninRoute: typeof SigninRoute
  TermsRoute: typeof TermsRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  AccountPrivacyRoute: typeof AccountPrivacyRoute
  AdvertiseBannersRoute: typeof AdvertiseBannersRoute
  AdvertiseListingTypesRoute: typeof AdvertiseListingTypesRoute
  AdvertisePremiumPlusRoute: typeof AdvertisePremiumPlusRoute
  AdvertiseVerifiedPhotosRoute: typeof AdvertiseVerifiedPhotosRoute
  ApiChatRoute: typeof ApiChatRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  MarketTrendsDemandRoute: typeof MarketTrendsDemandRoute
  MarketTrendsPricesRoute: typeof MarketTrendsPricesRoute
  MarketTrendsReportsRoute: typeof MarketTrendsReportsRoute
  PropertyIdRoute: typeof PropertyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-guides': {
      id: '/area-guides'
      path: '/area-guides'
      fullPath: '/area-guides'
      preLoaderRoute: typeof AreaGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-rent': {
      id: '/for-rent'
      path: '/for-rent'
      fullPath: '/for-rent'
      preLoaderRoute: typeof ForRentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-sale': {
      id: '/for-sale'
      path: '/for-sale'
      fullPath: '/for-sale'
      preLoaderRoute: typeof ForSaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-property': {
      id: '/list-property'
      path: '/list-property'
      fullPath: '/list-property'
      preLoaderRoute: typeof ListPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mortgage-calculator': {
      id: '/mortgage-calculator'
      path: '/mortgage-calculator'
      fullPath: '/mortgage-calculator'
      preLoaderRoute: typeof MortgageCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/privacy': {
      id: '/account/privacy'
      path: '/account/privacy'
      fullPath: '/account/privacy'
      preLoaderRoute: typeof AccountPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings': {
      id: '/admin/listings'
      path: '/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminListingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/photos': {
      id: '/admin/photos'
      path: '/photos'
      fullPath: '/admin/photos'
      preLoaderRoute: typeof AdminPhotosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/regions': {
      id: '/admin/regions'
      path: '/regions'
      fullPath: '/admin/regions'
      preLoaderRoute: typeof AdminRegionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/advertise/banners': {
      id: '/advertise/banners'
      path: '/advertise/banners'
      fullPath: '/advertise/banners'
      preLoaderRoute: typeof AdvertiseBannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise/listing-types': {
      id: '/advertise/listing-types'
      path: '/advertise/listing-types'
      fullPath: '/advertise/listing-types'
      preLoaderRoute: typeof AdvertiseListingTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise/premium-plus': {
      id: '/advertise/premium-plus'
      path: '/advertise/premium-plus'
      fullPath: '/advertise/premium-plus'
      preLoaderRoute: typeof AdvertisePremiumPlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise/verified-photos': {
      id: '/advertise/verified-photos'
      path: '/advertise/verified-photos'
      fullPath: '/advertise/verified-photos'
      preLoaderRoute: typeof AdvertiseVerifiedPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/enquiries': {
      id: '/dashboard/enquiries'
      path: '/enquiries'
      fullPath: '/dashboard/enquiries'
      preLoaderRoute: typeof DashboardEnquiriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/listings': {
      id: '/dashboard/listings'
      path: '/listings'
      fullPath: '/dashboard/listings'
      preLoaderRoute: typeof DashboardListingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/subscription': {
      id: '/dashboard/subscription'
      path: '/subscription'
      fullPath: '/dashboard/subscription'
      preLoaderRoute: typeof DashboardSubscriptionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/for-rent/commercial': {
      id: '/for-rent/commercial'
      path: '/commercial'
      fullPath: '/for-rent/commercial'
      preLoaderRoute: typeof ForRentCommercialRouteImport
      parentRoute: typeof ForRentRoute
    }
    '/for-rent/flats-apartments': {
      id: '/for-rent/flats-apartments'
      path: '/flats-apartments'
      fullPath: '/for-rent/flats-apartments'
      preLoaderRoute: typeof ForRentFlatsApartmentsRouteImport
      parentRoute: typeof ForRentRoute
    }
    '/for-rent/houses': {
      id: '/for-rent/houses'
      path: '/houses'
      fullPath: '/for-rent/houses'
      preLoaderRoute: typeof ForRentHousesRouteImport
      parentRoute: typeof ForRentRoute
    }
    '/for-rent/land': {
      id: '/for-rent/land'
      path: '/land'
      fullPath: '/for-rent/land'
      preLoaderRoute: typeof ForRentLandRouteImport
      parentRoute: typeof ForRentRoute
    }
    '/for-rent/vehicles': {
      id: '/for-rent/vehicles'
      path: '/vehicles'
      fullPath: '/for-rent/vehicles'
      preLoaderRoute: typeof ForRentVehiclesRouteImport
      parentRoute: typeof ForRentRoute
    }
    '/for-sale/commercial': {
      id: '/for-sale/commercial'
      path: '/commercial'
      fullPath: '/for-sale/commercial'
      preLoaderRoute: typeof ForSaleCommercialRouteImport
      parentRoute: typeof ForSaleRoute
    }
    '/for-sale/flats-apartments': {
      id: '/for-sale/flats-apartments'
      path: '/flats-apartments'
      fullPath: '/for-sale/flats-apartments'
      preLoaderRoute: typeof ForSaleFlatsApartmentsRouteImport
      parentRoute: typeof ForSaleRoute
    }
    '/for-sale/houses': {
      id: '/for-sale/houses'
      path: '/houses'
      fullPath: '/for-sale/houses'
      preLoaderRoute: typeof ForSaleHousesRouteImport
      parentRoute: typeof ForSaleRoute
    }
    '/for-sale/land': {
      id: '/for-sale/land'
      path: '/land'
      fullPath: '/for-sale/land'
      preLoaderRoute: typeof ForSaleLandRouteImport
      parentRoute: typeof ForSaleRoute
    }
    '/for-sale/vehicles': {
      id: '/for-sale/vehicles'
      path: '/vehicles'
      fullPath: '/for-sale/vehicles'
      preLoaderRoute: typeof ForSaleVehiclesRouteImport
      parentRoute: typeof ForSaleRoute
    }
    '/market-trends/demand': {
      id: '/market-trends/demand'
      path: '/market-trends/demand'
      fullPath: '/market-trends/demand'
      preLoaderRoute: typeof MarketTrendsDemandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-trends/prices': {
      id: '/market-trends/prices'
      path: '/market-trends/prices'
      fullPath: '/market-trends/prices'
      preLoaderRoute: typeof MarketTrendsPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-trends/reports': {
      id: '/market-trends/reports'
      path: '/market-trends/reports'
      fullPath: '/market-trends/reports'
      preLoaderRoute: typeof MarketTrendsReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/result': {
      id: '/payments/result'
      path: '/result'
      fullPath: '/payments/result'
      preLoaderRoute: typeof PaymentsResultRouteImport
      parentRoute: typeof PaymentsRoute
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/new': {
      id: '/requests/new'
      path: '/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof RequestsNewRouteImport
      parentRoute: typeof RequestsRoute
    }
    '/admin/listings/new': {
      id: '/admin/listings/new'
      path: '/new'
      fullPath: '/admin/listings/new'
      preLoaderRoute: typeof AdminListingsNewRouteImport
      parentRoute: typeof AdminListingsRoute
    }
    '/dashboard/listings/new': {
      id: '/dashboard/listings/new'
      path: '/new'
      fullPath: '/dashboard/listings/new'
      preLoaderRoute: typeof DashboardListingsNewRouteImport
      parentRoute: typeof DashboardListingsRoute
    }
  }
}

interface AdminListingsRouteChildren {
  AdminListingsNewRoute: typeof AdminListingsNewRoute
}

const AdminListingsRouteChildren: AdminListingsRouteChildren = {
  AdminListingsNewRoute: AdminListingsNewRoute,
}

const AdminListingsRouteWithChildren = AdminListingsRoute._addFileChildren(
  AdminListingsRouteChildren,
)

interface AdminRouteChildren {
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminListingsRoute: typeof AdminListingsRouteWithChildren
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminPhotosRoute: typeof AdminPhotosRoute
  AdminRegionsRoute: typeof AdminRegionsRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgentsRoute: AdminAgentsRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminListingsRoute: AdminListingsRouteWithChildren,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminPhotosRoute: AdminPhotosRoute,
  AdminRegionsRoute: AdminRegionsRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerificationRoute: AdminVerificationRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AgentsRouteChildren {
  AgentsIdRoute: typeof AgentsIdRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsIdRoute: AgentsIdRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface DashboardListingsRouteChildren {
  DashboardListingsNewRoute: typeof DashboardListingsNewRoute
}

const DashboardListingsRouteChildren: DashboardListingsRouteChildren = {
  DashboardListingsNewRoute: DashboardListingsNewRoute,
}

const DashboardListingsRouteWithChildren =
  DashboardListingsRoute._addFileChildren(DashboardListingsRouteChildren)

interface DashboardRouteChildren {
  DashboardEnquiriesRoute: typeof DashboardEnquiriesRoute
  DashboardListingsRoute: typeof DashboardListingsRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSubscriptionRoute: typeof DashboardSubscriptionRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardEnquiriesRoute: DashboardEnquiriesRoute,
  DashboardListingsRoute: DashboardListingsRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSubscriptionRoute: DashboardSubscriptionRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ForRentRouteChildren {
  ForRentCommercialRoute: typeof ForRentCommercialRoute
  ForRentFlatsApartmentsRoute: typeof ForRentFlatsApartmentsRoute
  ForRentHousesRoute: typeof ForRentHousesRoute
  ForRentLandRoute: typeof ForRentLandRoute
  ForRentVehiclesRoute: typeof ForRentVehiclesRoute
}

const ForRentRouteChildren: ForRentRouteChildren = {
  ForRentCommercialRoute: ForRentCommercialRoute,
  ForRentFlatsApartmentsRoute: ForRentFlatsApartmentsRoute,
  ForRentHousesRoute: ForRentHousesRoute,
  ForRentLandRoute: ForRentLandRoute,
  ForRentVehiclesRoute: ForRentVehiclesRoute,
}

const ForRentRouteWithChildren =
  ForRentRoute._addFileChildren(ForRentRouteChildren)

interface ForSaleRouteChildren {
  ForSaleCommercialRoute: typeof ForSaleCommercialRoute
  ForSaleFlatsApartmentsRoute: typeof ForSaleFlatsApartmentsRoute
  ForSaleHousesRoute: typeof ForSaleHousesRoute
  ForSaleLandRoute: typeof ForSaleLandRoute
  ForSaleVehiclesRoute: typeof ForSaleVehiclesRoute
}

const ForSaleRouteChildren: ForSaleRouteChildren = {
  ForSaleCommercialRoute: ForSaleCommercialRoute,
  ForSaleFlatsApartmentsRoute: ForSaleFlatsApartmentsRoute,
  ForSaleHousesRoute: ForSaleHousesRoute,
  ForSaleLandRoute: ForSaleLandRoute,
  ForSaleVehiclesRoute: ForSaleVehiclesRoute,
}

const ForSaleRouteWithChildren =
  ForSaleRoute._addFileChildren(ForSaleRouteChildren)

interface PaymentsRouteChildren {
  PaymentsResultRoute: typeof PaymentsResultRoute
}

const PaymentsRouteChildren: PaymentsRouteChildren = {
  PaymentsResultRoute: PaymentsResultRoute,
}

const PaymentsRouteWithChildren = PaymentsRoute._addFileChildren(
  PaymentsRouteChildren,
)

interface RequestsRouteChildren {
  RequestsNewRoute: typeof RequestsNewRoute
}

const RequestsRouteChildren: RequestsRouteChildren = {
  RequestsNewRoute: RequestsNewRoute,
}

const RequestsRouteWithChildren = RequestsRoute._addFileChildren(
  RequestsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AgentsRoute: AgentsRouteWithChildren,
  AreaGuidesRoute: AreaGuidesRoute,
  BlogRoute: BlogRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DevelopersRoute: DevelopersRoute,
  ForRentRoute: ForRentRouteWithChildren,
  ForSaleRoute: ForSaleRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  ListPropertyRoute: ListPropertyRoute,
  MortgageCalculatorRoute: MortgageCalculatorRoute,
  PaymentsRoute: PaymentsRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RegisterRoute: RegisterRoute,
  RequestsRoute: RequestsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  SigninRoute: SigninRoute,
  TermsRoute: TermsRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  AccountPrivacyRoute: AccountPrivacyRoute,
  AdvertiseBannersRoute: AdvertiseBannersRoute,
  AdvertiseListingTypesRoute: AdvertiseListingTypesRoute,
  AdvertisePremiumPlusRoute: AdvertisePremiumPlusRoute,
  AdvertiseVerifiedPhotosRoute: AdvertiseVerifiedPhotosRoute,
  ApiChatRoute: ApiChatRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  MarketTrendsDemandRoute: MarketTrendsDemandRoute,
  MarketTrendsPricesRoute: MarketTrendsPricesRoute,
  MarketTrendsReportsRoute: MarketTrendsReportsRoute,
  PropertyIdRoute: PropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
